"""add flow links

Revision ID: 9be5ff4cec39
Revises: 90b3733f06ba
Create Date: 2026-07-21 10:55:22.251497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be5ff4cec39'
down_revision: Union[str, Sequence[str], None] = '90b3733f06ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_flow_id', sa.Integer(), nullable=False),
    sa.Column('target_flow_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_flow_id'], ['flows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_flow_id'], ['flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_flow_id', 'target_flow_id', 'relation_type', name='uq_flow_link_relation')
    )
    op.create_index(op.f('ix_flow_links_source_flow_id'), 'flow_links', ['source_flow_id'], unique=False)
    op.create_index(op.f('ix_flow_links_target_flow_id'), 'flow_links', ['target_flow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_links_target_flow_id'), table_name='flow_links')
    op.drop_index(op.f('ix_flow_links_source_flow_id'), table_name='flow_links')
    op.drop_table('flow_links')
    # ### end Alembic commands ###
